import type { NextPage } from "next";
import Head from "next/head";
import BodySingle from "dh-marvel/components/layouts/body/single/body-single";
import { GridTemplate } from "dh-marvel/components/gridTemplate/gridTemplate";
import { Comic } from "dh-marvel/features/types";
import { getComics } from "dh-marvel/services/marvel/marvel.service";

type props = {
  comics: Comic[];
};
export async function getStaticProps() {
  const res = await getComics(0, 12);
  return {
    props: {
      comics: res.data.results,
    },
  };
}

const Index: NextPage<props> = ({ comics }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BodySingle title={"Todos los comics"}>
        <GridTemplate comics={comics} />
      </BodySingle>
    </>
  );
};

export default Index;
